[package]
name = "pvs6_to_mysql"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.14", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
regex = "1.11.1"
once_cell = "1.21.1"
mysql = "26.0.0"
myloginrs = "0.1"
